services:
  - type: web
    name: chamggae-backend
    runtime: java
    buildCommand: ./gradlew clean bootJar -x test
    startCommand: chmod +x start.sh && ./start.sh
    plan: free
    env: java17
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: modi-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: modi-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: modi-db
          property: password
      - key: KAKAO
        sync: false
      - key: KAKAO_REDIRECT_URI
        sync: false
      - key: KAKAO_BROWSER_REDIRECT_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        sync: false
      - key: GOOGLE_BUCKET_NAME
        sync: false
      - key: jwtKey
        sync: false
    healthCheckPath: /actuator/health
    disk:
      name: chamggae-disk
      mountPath: /data
      sizeGB: 1

# PostgreSQL 데이터베이스 추가
databases:
  - name: modi-db
    databaseName: modi-db
    user: modi_user
    plan: free
