spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      connection-init-sql: 'SELECT 1'
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    context-path: /
  port: ${PORT:8080}

logging:
  level:
    root: info
    com.example.demo: info
    com.zaxxer.hikari.pool: warn

mybatis:
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: 'mapper/*.xml'
  configuration:
    use-generated-keys: true

kakao:
  client-id: ${KAKAO}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  redirect-broswer-uri: ${KAKAO_BROWSER_REDIRECT_URI}

openai:
  key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}
  bucket-name: ${GOOGLE_BUCKET_NAME}

jwtKey: ${jwtKey}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
