spring:
  application:
    name: demo
  datasource:
    driver-class-name: ${DB_DRIVER:org.mariadb.jdbc.Driver}
    url: ${DB_EXTERNAL_URL:${DB_PATH}}
    username: ${DB_USERNAME:maka}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      connection-init-sql: 'SELECT 1'
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  # JPA/Hibernate 설정 추가
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: ${DB_DIALECT:org.hibernate.dialect.MariaDBDialect}
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MariaDBDialect}
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    context-path: /
  port: ${PORT:8080}

logging:
  level:
    root: info
    com.example.demo: info
    com.zaxxer.hikari.pool: warn

mybatis:
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: 'mapper/*.xml'
  configuration:
    use-generated-keys: true

kakao:
  client-id: ${KAKAO}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  redirect-broswer-uri: ${KAKAO_BROWSER_REDIRECT_URI}

openai:
  key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}
  bucket-name: ${GOOGLE_BUCKET_NAME}

# JWT 설정
jwtKey: ${jwtKey:default-secret-key-for-development-only}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CORS 설정 (필요시)
cors:
  allowed-origins:
    - 'http://localhost:3000'
    - 'https://localhost:3000'
    - 'https://modi-backend-th1n.onrender.com'
    - 'http://localhost:8080'
    - 'http://localhost:8090'
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  allowed-headers: '*'
  exposed-headers:
    - 'Authorization'
    - 'Content-Type'
    - 'X-Requested-With'
    - 'Accept'
    - 'Origin'
    - 'Access-Control-Request-Method'
    - 'Access-Control-Request-Headers'
  allow-credentials: true
  max-age: 3600
