spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_PATH:jdbc:mariadb://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true}
    username: ${DB_MARIA_USERNAME:root}
    password: ${DB_MARIA_PASSWORD:password}
    hikari:
      pool-name: hikari-pool-local
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      connection-init-sql: 'SELECT 1'
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 60000

server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    context-path: /

mybatis:
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: 'mapper/*.xml'
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

kakao:
  client-id: ${KAKAO}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  redirect-broswer-uri: ${KAKAO_BROWSER_REDIRECT_URI}

openai:
  key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}
  bucket-name: ${GOOGLE_BUCKET_NAME}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

cors:
  allowed-origins:
    - 'http://localhost:3000'
    - 'https://localhost:3000'
    - 'http://localhost:8080'
    - 'http://localhost:8090'
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  allowed-headers: '*'
  exposed-headers:
    - 'Authorization'
    - 'Content-Type'
    - 'X-Requested-With'
    - 'Accept'
    - 'Origin'
    - 'Access-Control-Request-Method'
    - 'Access-Control-Request-Headers'
  allow-credentials: true
  max-age: 3600

logging:
  level:
    root: info
    com.example.demo: debug
    com.zaxxer.hikari: debug
    com.zaxxer.hikari.pool: debug
  file:
    name: logs/application.log
