spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: hikari-pool-prod
      maximum-pool-size: 5 # RDS 환경에 맞게 조정
      minimum-idle: 2
      connection-timeout: 60000 # 타임아웃 증가 (네트워크 지연 고려)
      idle-timeout: 300000 # 5분
      max-lifetime: 900000 # 15분
      auto-commit: true
      leak-detection-threshold: 60000
      initialization-fail-timeout: 120000 # 2분
      keepalive-time: 300000 # 연결 유지
      validation-timeout: 30000 # 검증 타임아웃
      connection-init-sql: 'SELECT 1'
      # MariaDB SSL 설정
      data-source-properties:
        useSSL: true
        requireSSL: false
        verifyServerCertificate: false
        # 연결 검증을 위한 추가 설정
        applicationName: chamggae-backend
        tcpKeepAlive: true
        autoReconnect: true
        maxReconnects: 3

server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    context-path: /

mybatis:
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: 'mapper/*.xml'
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

kakao:
  client-id: ${KAKAO}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  redirect-broswer-uri: ${KAKAO_BROWSER_REDIRECT_URI}

openai:
  key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}
  bucket-name: ${GOOGLE_BUCKET_NAME}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    db:
      enabled: true
    datasource:
      enabled: true

cors:
  allowed-origins:
    - 'https://modi-backend-th1n.onrender.com'
    - 'http://localhost:3000'
    - 'https://localhost:3000'
    - 'http://localhost:8080'
    - 'http://localhost:8090'
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  allowed-headers: '*'
  exposed-headers:
    - 'Authorization'
    - 'Content-Type'
    - 'X-Requested-With'
    - 'Accept'
    - 'Origin'
    - 'Access-Control-Request-Method'
    - 'Access-Control-Request-Headers'
  allow-credentials: true
  max-age: 3600

logging:
  level:
    root: info
    com.example.demo: info
    com.zaxxer.hikari: debug # 데이터베이스 연결 디버깅을 위해 debug로 변경
    com.zaxxer.hikari.pool: debug
    org.springframework.jdbc: debug
    org.springframework.boot.autoconfigure.jdbc: debug
  file:
    name: logs/application.log
