spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_PATH}
    username: ${DB_USERNAME:maka}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      connection-init-sql: 'SELECT 1'
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 60000
      initialization-fail-timeout: -1

  # JPA/Hibernate 설정 추가
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
    open-in-view: false

server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    context-path: /
  port: ${PORT:8080}

logging:
  file:
    info: logs/info.log
    error: logs/error.log
  level:
    root: info
    com.example.demo: info
    com.zaxxer.hikari: debug
    com.zaxxer.hikari.pool: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.boot.autoconfigure: debug

mybatis:
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: 'mapper/*.xml'
  configuration:
    use-generated-keys: true

kakao:
  client-id: ${KAKAO}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  redirect-broswer-uri: ${KAKAO_BROWSER_REDIRECT_URI}

openai:
  key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}
  bucket-name: ${GOOGLE_BUCKET_NAME}

# JWT 설정
jwtKey: ${jwtKey}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CORS 설정 (필요시)
cors:
  allowed-origins:
    - 'https://modi-backend-th1n.onrender.com'
    - 'http://localhost:3000'
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: '*'
  allow-credentials: true
